[package]
name = "necessist-frameworks"
version = "0.1.0-beta.6"
edition = "2021"

description = "necessist-frameworks"

authors = ["Samuel Moelius <sam@moeli.us>"]
license = "AGPL"
repository = "https://github.com/trailofbits/necessist"

[dependencies]
necessist-core = { version = "=0.1.0-beta.6", path = "../core" }

anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
heck = "0.4"
if_chain = "1.0"
lazy_static = "1.4"
log = "0.4"
regex = "1.7"
remain = "0.2"
strum = "0.24"
strum_macros = "0.24"
subprocess = "0.2"
thiserror = "1.0"
walkdir = "2.3"

# Foundry
solang-parser = "0.2"

# Golang
tree-sitter = "0.20"
tree-sitter-go = "0.19"

# Hardhat TS
swc_core = { version = "0.59", features = ["common", "ecma_ast", "ecma_parser", "ecma_visit"] }

# Rust
cargo_metadata = "0.15"
syn = { version = "1.0", features = ["extra-traits", "full", "visit"] }

[dev-dependencies]
curl = "0.4"

[build-dependencies]
cargo_metadata = "0.15"
curl = "0.4"
heck = "0.4"
syn = "1.0"
