[package]
name = "necessist"
version = "0.1.0-beta.6"
edition = "2021"

description = "necessist"

authors = ["Samuel Moelius <sam@moeli.us>"]
license = "AGPL"
repository = "https://github.com/trailofbits/necessist"

[dependencies]
necessist-core = { version = "=0.1.0-beta.6", path = "../core", features = ["clap"] }
necessist-frameworks = { version = "=0.1.0-beta.6", path = "../frameworks" }

anyhow = "1.0"
clap = { version = "4.1", features = ["cargo", "derive"] }
env_logger = "0.10"

[workspace]
